### ISSUE TITLE
plaid-ruby library overhaul

### ISSUE THREAD

**Issue by michaelckelly** [plaid/plaid-ruby#106]
@all - 

Plaid is in the process of a major overhaul to the plaid-ruby library. Once completed, plaid-ruby will be an officially supported Plaid API client library. Our goals are to make the library more consistent and up-to-date with the API, more robust when it comes to error handling, and better documented (to name a few)!

Keep an eye out for a additional details and a release in the next few weeks!

**Comment by be9** [comment]
@all The 2.0.0.alpha release has just landed! Be sure to read the [new README](https://github.com/plaid/plaid-ruby/blob/master/README.md) and check the [UPGRADING](https://github.com/plaid/plaid-ruby/blob/master/UPGRADING.md) document which details the changes needed to be made to use 2.0.0.

Your feedback is welcome!

**Comment by dmerrick** [comment]
Hey Oleg, nice work!

Some comments:
* I like how well you documented all of the methods, but from what I can tell there are some "Internal" methods that are not `private`/`protected`, is there a reason for this?
* I'd like to see methods that modify the caller end with an `!` (as is the Ruby custom). For example, `Plaid::User.update!`, `Plaid::User.delete!`.
* Not crazy important, but for `Plaid::Client.env`, `:api` vs `:tartan` feels kind of awkward, perhaps it should be `:production` and `:tartan`? I get that it comes from the subdomain in the URL, but `env = :api` just feels weird to me.
* I'd like to add `rubocop` and run it over the new codebase. There are a lot of overly nitpicky checks (like methods being longer than 10 lines or whatever), but for ongoing code consistency it would be nice to fix some of the stylistic stuff (I can do this if you like).

**Comment by be9** [comment]
@dmerrick Let me respond to your comments.

1. "Public" vs. "Internal" is a more subtle distinction which can't be replaced by marking all the internal details as private or protected. E.g. there's a class `Connector` which is intended to use only inside the library. It's a separate class and should have its methods public to be accessible at all. However, its interface it's not guaranteed to stay the same in future. Also, most of the class constructors are marked as Internal. I don't expect my users to instantiate `Plaid::Category` by hand, for example. OTOH, I can't make the constructor private because it still gets called from `Plaid::User`.

2. The Ruby tradition doesn't encourage you to make all modifying methods end with `!`. Apparently Ruby is an OOP language where in-place mutation is expected by people (unlike e.g. Clojure, where everything is immutable by default). So the [Ruby style guide](https://github.com/bbatsov/ruby-style-guide#dangerous-method-bang) says that `!` is to be appended when there's a safe version of the same method (non-mutating, non-raising, etc.).
Speaking of Ruby standard library, all things like `map!`, `select!` have their non-mutating counterparts: `map`, `select`. OTOH, `Array#push` is a mutator (returns the same array with element added) but it's not named `push!`. As such, `Plaid::User#update` and `Plaid::User#delete` better keep their names, as they have no "safe" counterparts.

3. I think we could just make the code recognize `:production` in addition to `:api` (with stressing `:production` in the documentation).

4. I use SpaceMacs, and it kinda runs rubocop all the time. What we have mostly is "too long methods" and "Assignment Branch Condition size too high". `User` class is also "too long".  BTW I ran Code Climate: https://codeclimate.com/github/plaid/plaid-ruby/issues, it reported only a couple of minor issues.

**Comment by dmerrick** [comment]
Alright, all of those answers seem reasonable to me. Thanks for your work on this!

**Comment by JCBarry** [comment]
+1 to `:production` over `:api` as it is consistent with the environment config of Plaid Link as well.  Thanks for your hard work on this -- great improvements!

**Comment by be9** [comment]
@dmerrick  @JCBarry JC Addressed `:production` in #111

**Comment by be9** [comment]
@all Just merged two PRs and released them as 2.0.0.alpha.2.

**Comment by be9** [comment]
@all I've just released the 2.0.0! 🌞

**Comment by be9** [comment]
Thanks everyone, I think we can close this.
