### ISSUE TITLE
Retriving transaction and account details of a user

### ISSUE THREAD

**Issue by balakarthik2011** [plaid/plaid-ruby#128]
I am facing problem while retrieving the transaction and account details of the user, I have model user and in the user table i am storing the plaid access token
While i am trying to retrieve the user's transaction and account details
`user = User.first.plaid_access_token`
`plaid_user = Plaid::User.load(:connect, user.plaid_access_token)`

the ruturned user instance contains the accounts array as nil
```
>> plaid_user.accounts
nil
```
after getting the transactions using

`plaid_user.transactions`

the plaid_user which is the user instance is loaded with accounts details,

```
>> plaid_user.accounts
[#<Plaid::Account id="xxyyxxyyy", type=:depository, name="xxxxxx", institution=:chase>]
```

** i have changed the name and account id

I don't why the user instance is not having any data after loading, and how it gets the account details after getting the transaction details.

I need to know if i am making any mistakes..!

**Comment by be9** [comment]
You are not making any mistakes, @balakarthik2011.

The `User#load` method doesn't do any actual API calls, it just returns a prepared Plaid::User instance with token and product set. That's why you get `nil`: no data is yet available and `User#accounts` doesn't do any calls on its own.

However, upon calling `User#transactions` account information is obtained along with transactions and cached inside the user instance, henceforth `plaid_user.accounts` returns the account details.

Sorry if this behavior is unexpected. Things work this way to save Plaid API calls for you, as all API calls return account information as part of the response.

**Comment by balakarthik2011** [comment]
Thanks for your concern @be9 ,
I will use
```
plaid_user = Plaid::User.load(:connect, user.plaid_access_token)

plaid_user.balance
```
for getting the user accounts

**Comment by be9** [comment]
It's the best way to get the account information. :+1:

**Comment by jacobnbrum** [comment]
So does calling plaid_user.balance return the actual balances of the accounts? Because I tried calling 

`$ plaid_user.balance`
And all I am receiving is
```

[#<Plaid::Account id="QPO8J435dfgdfb4etdKfhg1yUdmXOwK", type=:depository, name="Plaid Savings", institution=:fake_institution>, #<Plaid::Account id="nban4wnPKEtnmEdfg445gD7pnCaeDBMy", type=:depository, name="Plaid Checking", institution=:fake_institution>, #<Plaid::Account id="XARE85EJqKsjxb4t43rtt3bb354bmRdOo", type=:depository, name="Plaid Premier Checking", institution=:fake_institution>, #<Plaid::Account id="pJPM4Ldfgb44terbJQrQbgU6kq37k", type=:credit, name="Plaid Credit Card", institution=:fake_institution>]
```

without any account balance information.
