### ISSUE TITLE
mfa_step for update always uses POST, instead of PATCH for update

### ISSUE THREAD

**Issue by gabrielgarza** [plaid/plaid-ruby#146]
From the code, I see that there is an @mfa_patch instance variable and based on that it uses wither`POST` or`PATCH`: https://github.com/plaid/plaid-ruby/blob/master/lib/plaid/user.rb#L215

But my issue is that that value for the `@mfa_patch` doesn't persist across API calls from my client so I believe it's always doing a post even if I did a `user.update` right before.

I'm thinking of submitting a pull request to either create a different function i.e. `update_mfa_step` or to make the `mfa_step` function send a `PATCH` if that if there is an `options[:update] == true` option passed in the options hash of `mfa_step(info = nil, send_method: nil, options: nil)`

Any suggestions? @be9 

Thanks!

**Comment by be9** [comment]
@gabrielgarza I think the `options[:update]` would be a solution here.

**Comment by dam13n** [comment]
@gabrielgarza any progress on this? I am the point that i need this addressed too.

Can we add `attr_reader: :mfa_patch` to `Plaid::User` so we can check the value? Or maybe `attr_accessor`, so we can set ourselves temporarily.

Even fixing this though, I have an actual US Bank account connected w/ Plaid that is returning a 1215, which is an `mfa_reset` with the `resolve`= "MFA access has changed or this application's access has been revoked. Submit a PATCH call to resolve." Pretty sure it's because I answered one of the MFA questions wrong.

However, here's the response from the `update` call:
```
#<Plaid::User:0x007fca29df2500
 @access_token=<hidden>,
 @accounts=nil,
 @client=nil,
 @income=nil,
 @info=nil,
 @initial_transactions=nil,
 @mfa=nil,
 @mfa_required=nil,
 @mfa_type=nil,
 @product=:connect,
 @risk=nil,
 @stripe_bank_account_token=nil>
```
`@mfa_required` is not getting set properly, which means the `Connector` isn't getting a 201 response...presumably since this freaking gem obfuscates everything. So looks like the `@mfa_patch` isn't get setting to `true` regardless.

On top of this, but a separate issue I think, is that that account did successfully pull the account data (name, balance...) on the initial connect for some reason, but gives the 1215 error when trying to subsequently pull transactions. I have this bank successfully connected on a side account, so you can rule out issues on the bank side.

**Comment by gabrielgarza** [comment]
@dam13n thanks for the reminder.. I've made the fix and will submit the PR tomorrow

**Comment by gabrielgarza** [comment]
pull request submitted.

**Comment by edmundloo** [comment]
Major version bump invalidates issue.
