### ISSUE TITLE
user.balance vs user.transactions

### ISSUE THREAD

**Issue by rubendinho** [plaid/plaid-ruby#153]
I realize this may be more of an API question, but at the very least, it would be great to improve the documentation on the distinction between the two methods. 

This morning we started experiencing a problem with `user.balance`, which is timing out without any error, while `user.transactions` is working as expected.  

What's the preferred method to use when you only need to return `user.accounts` data?  

Thanks,
Ruben

**Comment by michaelckelly** [comment]
@rubendinho  - `user.balance` makes a call to our [`/balance` API endpoint][1], which retrieves real-time balances for each account associated with the access token. This means that Plaid needs to communicate with the financial institution in order to pull the data, which can take some time and varies by institution (and other factors).

`user.transactions` makes a call to our [`/connect/` API endpoint][2] to retrieve transaction data for the access token. This call does not trigger any communication with the financial institution, so it's generally faster and more reliable from a timing perspective.

[1]: https://plaid.com/docs/api/#get-transactions
[2]: https://plaid.com/docs/api/#get-balance

**Comment by edmundloo** [comment]
Major version bump invalidates issue.
