### ISSUE TITLE
How to pass USAA account credentials?

### ISSUE THREAD

**Issue by dam13n** [plaid/plaid-ruby#18]
I've tried passing a 'pin' or 'PIN' in the base json call and in a credentials hash, as well as passing the pin the regular mfa paramters. I can't get it to work. Anyone got it to work? Have a gist?

**Comment by michaelckelly** [comment]
Hi Damien--

I'm a bit late here, but to answer your question, you were encountering a small bug with our USAA integration that was recently fixed.  Adding this account should succeed and/or prompt you with MFA questions as expected.

**Comment by demosophy** [comment]
Can you expand a bit more?  I can't get Plaid.auth to work with USAA because the function doesn't accept PIN as an argument.  I looked at the source and can't find any support for a PIN.  Omitting the PIN gives:

'''ruby
[16] pry(main)> user = Plaid.auth('connect','plaid_test','plaid_good','usaa')
RuntimeError: The request was malformed. Did you check the API docs?
from /Users/lmossburg/.rvm/gems/ruby-2.1.5@stopcharge/gems/plaid-1.0.1/lib/plaid/util.rb:23:in `error_handler'
'''

**Comment by dam13n** [comment]
Demosophy, there is a lot missing from both gem versions. You'll need to add the functionality yourself or do a manual call. USAA is working currently if passed a 'pin' parameter.

**Comment by j4ustin** [comment]
@

**Comment by j4ustin** [comment]
@dam13n, please ping me on issues needing attention. I can build and release versions or approve PRs from now on.

**Comment by dam13n** [comment]
@j4ustin sweeeeet. will do!

**Comment by demosophy** [comment]
I created a pull request that should do the trick.  feedback welcome

**Comment by j4ustin** [comment]
@demosophy @dam13n The latest version of the gem (V1.1.0) now has the pin included as an optional parameter in the AddUser module.

**Comment by dshumakerUT** [comment]
Just got off support line with USAA. Their official policy as of 2/23/21 , they do not support privacy.com (plaid).  Major bummer.  I asked the support person to add a "Please support plaid" request. and he did..  fwiw.
