### ISSUE TITLE
item ids

### ISSUE THREAD

**Issue by sarink** [plaid/plaid-ruby#184]
Why am I getting item_ids that are just strings? They're not uuids, they're not integers... we're supposed to secure and persist them in the database and reference them, but they're just strings? I don't want to index my table on a string :-/

**Comment by michaelckelly** [comment]
@sarink - Item IDs are hexadecimal strings, 32 characters in length. Item IDs are the included identifier in Plaid webhook payloads, so we do recommending storing the item ID in a way that makes it easy & fast to look up. You could also store a map of item ID <-> user ID and avoid storing the item ID in your primary user collection.

Also, since your users may have multiple Plaid items (and access_tokens), I'd suggest making sure that you can handle a many-to-one relationship between items and users.

**Comment by sarink** [comment]
Hey @michaelckelly, the `item_id`s I'm getting back are neither hexadecimal or 32 characters in length... example: `Z147oVvawkFkLgbGpyEVhNXVv3MwmvhnMnDjx` (this is from sandbox mode)

**Comment by michaelckelly** [comment]
> Hey @michaelckelly, the item_ids I'm getting back are neither hexadecimal nor 32 characters in length (they appear to be 37 characters, but still not hex). In any case, I guess I need to figure out a way to index them so they can be accessed efficiently.

Thanks for correcting that, @sarink  - that was a mistake on my part!

**Comment by be9** [comment]
@sarink string indices work well in any modern relational or non-relational database.
