### ISSUE TITLE
INVALID_PUBLIC_TOKEN

### ISSUE THREAD

**Issue by Bilal-Abbas** [plaid/plaid-ruby#268]
`client.item.public_token.exchange(source.token)`

the source is a bank account and token is a stripe generated token

My environment is 

`Rails.env.production? ? :production : :sandbox`

I am consistently getting 

> provided public token is in an invalid format. expected format: public-<environment>-<identifier>

My public key is 

> 93*****************************18

Any suggestions?

**Comment by otherchen** [comment]
Hi @Bilal-Abbas, the public_token exchange expects the `source.token` to be a public_token, not a stripe generated token which is why you're getting that error. 

You can refer to the [docs](https://plaid.com/docs/#exchange-token-flow) for more details on how to get a valid public_token after connecting your account through Plaid. Essentially, a valid public_token will be passed into the `onSuccess` callback for Plaid Link which you'll need to send into this exchange function.
