### ISSUE TITLE
Institutions endpoint returns error when requesting include_institution_data flag

### ISSUE THREAD

**Issue by connor-odoherty** [plaid/plaid-ruby#322]
When attempting to to use the institutions endpoint to grab optional metadata like so:

```
client.institutions.get count: 1,
                                     offset: 1,
                                     country_codes: ['US'], 
                                     options: { products: ['transactions'],
                                                      include_optional_metadata: true }
```

the API responds with an error:

```
Error Type      : INVALID_REQUEST
Error Code      : INVALID_FIELD
Error Message   : This endpoint does not support include_optional_metadata.
```

According to the documentation [here](https://plaid.com/docs/api/institutions/#institutions-get-request-include-optional-metadata) and the tests defined [here](https://github.com/plaid/plaid-ruby/blob/f1b9d83fd9175eec5684307fb6c6fd9b60204c1d/test/test_institutions.rb), this should be a valid request.

Is there an undocumented restriction on that flag? I am in the sandbox env, is this only available in development and production?

**Comment by phoenixy1** [comment]
@connor-odoherty I apologize that this issue slipped through the cracks and that it took us such a long time to get back to you. I looked into it and it turns out that using this flag may require your account to be specially enabled for it by your Plaid account manager. I will make sure that our documentation is updated to reflect this fact.
