### ISSUE TITLE
User.transactions not returning Plaid::User::Transaction

### ISSUE THREAD

**Issue by fredkelly** [plaid/plaid-ruby#34]
I'm getting a user with an existing access_token in the following way:

```ruby
  def build_plaid_user
    @plaid_user ||= Plaid::User.new
    @plaid_user.permissions = %w{connect}
    @plaid_user.access_token = self.access_token
    @plaid_user
  end
```

I'm then trying to get transactions:
```ruby
  def retrieve_transactions
    @plaid_user.get_connect
    @plaid_user.transactions
    # => [ ["eJXpMzpR65FP4RYno6yjhBDxgkM6pXC9RKM9o3", "QPO8Jo8vdDHMepg41PBwckXm4KdK1yUdmXOwK", -3042.44, "Company Payroll", {"location"=>{}}, nil, false, {"location"=>{}, "name"=>1}, {"primary"=>"special"}, ["Transfer", "Payroll"], "21009000"] , ... ]
  end
```

As you can see the return value is an array of arrays, rather than transaction objects. Is there a better way to do this so I can get `Plaid::User::Transaction` instances?

**Comment by j4ustin** [comment]
@fredkelly Using the new method I introduced earlier you should now be able to call Plaid.set_user('access_token',['auth','connect','info'],'type') -- note: type is optional, if you have the new access tokens you can omit that -- and automatically have the user built back to the original state. 

Let me know if this is still a problem, otherwise ping me here and we'll shut the issue down.

**Comment by fredkelly** [comment]
Hey Justin, looks great - thanks!
