### ISSUE TITLE
Ruby 3.0 support

### ISSUE THREAD

**Issue by clarkedb** [plaid/plaid-ruby#407]
The README says Ruby 2.4+, but I wanted to check is `plaid` is compatible with Ruby 3.0 and is there is a known version of the gem that introduced ruby 3 support? I couldn't tell from the docs.

**Comment by phoenixy1** [comment]
As far as I know there are no limitations on Ruby 3 support in the latest version of the Plaid client libraries -- I just did some smoke testing with the Quickstart (which uses a recent version of the client libraries) against Ruby 3.1 and it seems to work fine. I'm not sure when Ruby 3 support was introduced.

**Comment by javierjulio** [comment]
This should be reopened. I was curious about this and looked into the CI setup. CI only runs tests against Ruby 2.4 which went EOL 2 years ago. Is there a reason CI doesn't run the test suite against most or all currently supported versions of Ruby, including 3.0?

**Comment by phoenixy1** [comment]
2.4 is the minimum Ruby version supported by the OpenAPI generator we use, which is why we test against it. Changing Ruby versions used in CI is not a high priority; we currently have hundreds of customers using the generated Ruby client libraries and have yet to receive any reports of the libraries behaving differently on different Ruby versions or have any other reason to believe that the behavior is version-sensitive.
