### ISSUE TITLE
Creating a Plaid::ApiError object with a string as argument doesn't work as intended

### ISSUE THREAD

**Issue by phharvie** [plaid/plaid-ruby#457]
The documentation in the `Plaid::ApiError` says an error can be created in the following ways:
```
# Usage examples:
#   ApiError.new
#   ApiError.new("message")
#   ApiError.new(:code => 500, :response_headers => {}, :response_body => "")
#   ApiError.new(:code => 404, :message => "Not Found")
```
However, creating an error with a string as the argument (second usage) doesn't work as intended.
```ruby
# expected behavior
error = ApiError.new('Connection timed out')
error.message
=> "Connection timed out"

# actual behavior
error = ApiError.new('Connection timed out')
error.message
=> "Error message: the server returns an error"
```
The actual error message is the default error message for the class. This makes it difficult to implement custom error handling of timeouts, since the error message for timeouts is not distinct

**Comment by JoshHaver** [comment]
Seconding this issue

**Comment by JoshHaver** [comment]
Hello plaid team 👋 From your [gemspec](https://github.com/plaid/plaid-ruby/blob/v23.0.0/plaid.gemspec) file, it looks like the latest plaid gem version uses `openapi-generator` version 6.1.0. According to the [changelog](https://github.com/OpenAPITools/openapi-generator/releases) of `openapi-generator`, the issue that caused this message bug was fixed in version [6.3.0](https://github.com/OpenAPITools/openapi-generator/releases/tag/v6.3.0). 

Could you please update to version 6.3.0 of `openapi-generator` so that this issue can be fixed? 🙏 🙇

**Comment by phoenixy1** [comment]
@JoshHaver thanks for looking into this and diagnosing it! Updating the openapi generator versions is always a little fiddlier than it should be, but I'll put this on the to-do list

**Comment by phoenixy1** [comment]
We've just merged an update to generate the ruby clib with version 6.3.0 of the generator, so this should be fixed with next week's post-Thanksgiving release

**Comment by phoenixy1** [comment]
The release vehicle for this shipped on monday, so I'm closing this out. Feel free to re-open if it's still happening with the latest version.
