### ISSUE TITLE
Recurring Transfer status cancelled invalid date (Date::Error)

### ISSUE THREAD

**Issue by neb417** [plaid/plaid-ruby#463]
Once a recurring payment is cancelled, then calling transfer recurring get returns an empty string for the `next_origination_date`  causing `invalid date (Date::Error)` in model recurring_transfer.rb:369. See PR [#462](https://github.com/plaid/plaid-ruby/pull/462) for potential fix.

**Comment by phoenixy1** [comment]
Thank you for reporting this issue! We cannot accept PRs for the client libraries since they are auto-generated from an internal specification file. The issue has been fixed in the internal API specification file and this fix will be propagated to the client library in our next release, currently scheduled for later this month.
